export const FETCH_MEMES_SUCCESS = "FETCH_MEMES_SUCCESS";
export const FETCH_MEMES_FAILURE = "FETCH_MEMES_FAILURE";

export const GET_SINGLE_MEME_SUCCESS = "GET_SINGLE_MEME_SUCCESS";
export const GET_SINGLE_MEME_FAILURE = "GET_SINGLE_MEME_FAILURE";

export const GET_DATA_URL = "GET_DATA_URL";
